# Generated by Django 4.2.15 on 2025-09-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
